-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 16:02:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdsupermercado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdsupermercado` ;

-- -----------------------------------------------------
-- Schema bdsupermercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsupermercado` DEFAULT CHARACTER SET utf8 ;
USE `bdsupermercado` ;

-- -----------------------------------------------------
-- Table `bdsupermercado`.`Frutas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsupermercado`.`Frutas` ;

CREATE TABLE IF NOT EXISTS `bdsupermercado`.`Frutas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `precio` FLOAT NULL,
  `fechadecreacion` DATETIME NULL,
  `fechadeactualizacion` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsupermercado`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdsupermercado`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `bdsupermercado`.`Pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valortotal` FLOAT NULL,
  `fechadecreacion` DATETIME NULL,
  `fechadeactualizacionl` DATETIME NULL,
  `listadefrutas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedidos_Frutas_idx` (`listadefrutas` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Frutas`
    FOREIGN KEY (`listadefrutas`)
    REFERENCES `bdsupermercado`.`Frutas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bdsupermercado`.`Frutas`
-- -----------------------------------------------------
START TRANSACTION;
USE `bdsupermercado`;
INSERT INTO `bdsupermercado`.`Frutas` (`id`, `tipo`, `cantidad`, `precio`, `fechadecreacion`, `fechadeactualizacion`) VALUES (1, 'Pera', 2, 2.000, '2023-01-01 00:00:01', '2023-01-01 00:00:01');
INSERT INTO `bdsupermercado`.`Frutas` (`id`, `tipo`, `cantidad`, `precio`, `fechadecreacion`, `fechadeactualizacion`) VALUES (2, 'Manzana', 2, 1.000, '2023-01-01 00:00:01', '2023-01-01 00:00:01');

COMMIT;

